/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iniciar sesión */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cerrar la sesión actual */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener la sesión y el estado de acceso actuales */
        get: operations["getCurrentSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cambiar la contraseña actual */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar materias disponibles */
        get: operations["listSubjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subjectId}/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar materiales de una materia */
        get: operations["listSubjectMaterials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials/{materialId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener la ficha de un material */
        get: operations["getMaterial"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials/{materialId}/viewer-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear una sesión de lectura protegida */
        post: operations["createViewerSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/viewer-sessions/{viewerSessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cerrar una sesión de lectura */
        delete: operations["closeViewerSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/viewer-sessions/{viewerSessionId}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener manifiesto y tokens cortos de páginas cercanas */
        get: operations["getViewerManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/viewer-sessions/{viewerSessionId}/pages/{pageNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener una página autorizada con watermark incrustado */
        get: operations["getViewerPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar usuarios */
        get: operations["adminListUsers"];
        put?: never;
        /** Crear usuario estudiante */
        post: operations["adminCreateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener un usuario */
        get: operations["adminGetUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cambiar estado o datos administrables de un usuario */
        patch: operations["adminUpdateUser"];
        trace?: never;
    };
    "/admin/users/{userId}/access-extensions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extender manualmente la vigencia de acceso */
        post: operations["adminExtendUserAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar documentos y su procesamiento */
        get: operations["adminListDocuments"];
        put?: never;
        /** Cargar un PDF privado a cuarentena */
        post: operations["adminUploadDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar un documento y su procesamiento */
        get: operations["adminGetDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar metadatos o archivar un documento */
        patch: operations["adminUpdateDocument"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
            /** @default false */
            remember_me: boolean;
            /** Format: uuid */
            device_id: string;
            device_name: string;
        };
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        /** @enum {string} */
        Role: "student" | "admin";
        /** @enum {string} */
        UserStatus: "active" | "suspended" | "revoked";
        /** @enum {string} */
        AccessState: "active" | "expiring" | "expired" | "suspended" | "revoked";
        /** @enum {string} */
        ProblemCode: "AUTH_INVALID_CREDENTIALS" | "AUTH_REQUIRED" | "SESSION_EXPIRED" | "SESSION_REVOKED" | "ACCESS_EXPIRED" | "ACCOUNT_SUSPENDED" | "ACCOUNT_REVOKED" | "ADMIN_REQUIRED" | "RESOURCE_NOT_FOUND" | "VALIDATION_FAILED" | "RATE_LIMITED" | "IDEMPOTENCY_CONFLICT" | "RESOURCE_CONFLICT" | "BUSINESS_RULE_VIOLATION" | "VIEWER_UNAVAILABLE" | "PAYLOAD_TOO_LARGE" | "UNSUPPORTED_MEDIA_TYPE" | "INTERNAL_ERROR";
        SessionUser: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            status: components["schemas"]["UserStatus"];
            access_state: components["schemas"]["AccessState"];
            /** Format: date-time */
            access_until: string | null;
            must_change_password: boolean;
        };
        Session: {
            /**
             * Format: uuid
             * @description Identificador público; no es el secreto de cookie.
             */
            id: string;
            user: components["schemas"]["SessionUser"];
            /** Format: uuid */
            device_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            idle_expires_at: string;
            /** Format: date-time */
            absolute_expires_at: string;
        };
        SessionEnvelope: {
            data: components["schemas"]["Session"];
        };
        Subject: {
            id: string;
            name: string;
            description: string;
            material_count: number;
        };
        /** @enum {string} */
        MaterialType: "note" | "guide" | "book" | "mock_exam";
        Material: {
            id: string;
            subject_id: string;
            title: string;
            type: components["schemas"]["MaterialType"];
            page_count: number;
            /** Format: date-time */
            published_at: string;
            /** Format: date-time */
            updated_at: string;
            viewer_available: boolean;
            reading_progress?: components["schemas"]["ReadingProgress"] | null;
        };
        ReadingProgress: {
            page: number;
            percentage: number;
            /** Format: date-time */
            updated_at: string;
        };
        PageMeta: {
            page_size: number;
            has_more: boolean;
            next_cursor: string | null;
        };
        MaterialPage: {
            data: components["schemas"]["Material"][];
            meta: components["schemas"]["PageMeta"];
        };
        /**
         * @default normal
         * @enum {string}
         */
        PageVariant: "normal" | "high";
        ViewerSession: {
            /** Format: uuid */
            id: string;
            material_id: string;
            page_count: number;
            variant: components["schemas"]["PageVariant"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at: string;
            /** @example 15 */
            heartbeat_interval_seconds: number;
        };
        ViewerManifest: {
            session: components["schemas"]["ViewerSession"];
            image_width: number;
            image_height: number;
            pages: {
                page: number;
                token: string;
                /** Format: date-time */
                expires_at: string;
            }[];
        };
        AdminUser: components["schemas"]["SessionUser"] & {
            last_device_name?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateUserRequest: {
            name: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            access_until: string;
        };
        CreatedUser: {
            user: components["schemas"]["AdminUser"];
            /** @description Se devuelve una sola vez y nunca se persiste en claro. */
            initial_password: string;
        };
        UpdateUserRequest: {
            name?: string;
            status?: components["schemas"]["UserStatus"];
            reason?: string;
        };
        AccessExtension: {
            /** Format: uuid */
            user_id: string;
            /** Format: date-time */
            before: string | null;
            /** Format: date-time */
            after: string;
            reason: string;
            /** Format: date-time */
            created_at: string;
        };
        UserPage: {
            data: components["schemas"]["AdminUser"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** @enum {string} */
        DocumentStatus: "quarantined" | "queued" | "processing" | "ready" | "failed" | "rejected" | "archived";
        AdminDocument: {
            /** Format: uuid */
            id: string;
            title: string;
            subject_id: string;
            type: components["schemas"]["MaterialType"];
            status: components["schemas"]["DocumentStatus"];
            processing_progress: number;
            page_count?: number | null;
            safe_failure_code?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AdminDocumentPage: {
            data: components["schemas"]["AdminDocument"][];
            meta: components["schemas"]["PageMeta"];
        };
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            code: components["schemas"]["ProblemCode"];
            /** Format: uuid */
            request_id: string;
            retry_after_seconds?: number;
        };
        AccessProblem: components["schemas"]["Problem"] & {
            access_state?: components["schemas"]["AccessState"];
        };
        ValidationProblem: components["schemas"]["Problem"] & {
            errors: {
                field: string;
                code: string;
            }[];
        };
    };
    responses: {
        /** @description Credenciales inválidas, sin revelar si la cuenta existe. */
        InvalidCredentials: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.example.com/problems/invalid-credentials",
                 *       "title": "No pudimos iniciar sesión",
                 *       "status": 401,
                 *       "code": "AUTH_INVALID_CREDENTIALS",
                 *       "request_id": "9b191d15-c7f7-4b2a-97a0-190681a74fa8"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Falta una sesión válida. */
        Unauthenticated: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Acceso vencido, suspendido, revocado o sin permiso. */
        AccessDenied: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["AccessProblem"];
            };
        };
        /** @description Se requiere rol administrador. */
        AdminRequired: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Recurso inexistente o no visible para la cuenta. */
        NotFound: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Conflicto con el estado actual o un recurso existente. */
        Conflict: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description La clave ya se utilizó con un cuerpo diferente. */
        IdempotencyConflict: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description La operación incumple una regla de negocio. */
        BusinessRuleError: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Uno o más campos no son válidos. */
        ValidationError: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
        /** @description Documento reprocesándose o sesión de lectura no utilizable. */
        ViewerUnavailable: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Límite temporal excedido. */
        RateLimited: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Archivo por encima del límite configurado. */
        PayloadTooLarge: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Tipo real del archivo no admitido. */
        UnsupportedMedia: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description UUID único por intención; se conserva al reintentar la misma operación. */
        IdempotencyKey: string;
        Cursor: string;
        PageSize: number;
        SubjectId: string;
        MaterialId: string;
        ViewerSessionId: string;
        UserId: string;
        DocumentId: string;
    };
    requestBodies: never;
    headers: {
        /** @description Identificador de correlación de la solicitud. */
        RequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Sesión creada. También envía la cookie de sesión segura. */
            200: {
                headers: {
                    /** @example __Host-aula_session=opaque; Path=/; Secure; HttpOnly; SameSite=Lax */
                    "Set-Cookie"?: string;
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelope"];
                };
            };
            401: components["responses"]["InvalidCredentials"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión revocada y cookie eliminada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    getCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión válida. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID único por intención; se conserva al reintentar la misma operación. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Contraseña cambiada y demás sesiones revocadas. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BusinessRuleError"];
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    listSubjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Materias autorizadas para la cuenta. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": [
                     *         {
                     *           "id": "anatomia",
                     *           "name": "Anatomía",
                     *           "description": "Estructuras, sistemas y organización del cuerpo humano.",
                     *           "material_count": 6
                     *         },
                     *         {
                     *           "id": "biologia",
                     *           "name": "Biología",
                     *           "description": "Célula, genética y fundamentos de los seres vivos.",
                     *           "material_count": 6
                     *         },
                     *         {
                     *           "id": "histologia",
                     *           "name": "Histología",
                     *           "description": "Tejidos, microscopía y organización celular.",
                     *           "material_count": 6
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        data: components["schemas"]["Subject"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AccessDenied"];
        };
    };
    listSubjectMaterials: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                page_size?: components["parameters"]["PageSize"];
                query?: string;
                type?: components["schemas"]["MaterialType"];
            };
            header?: never;
            path: {
                subjectId: components["parameters"]["SubjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de materiales publicados. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    getMaterial: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                materialId: components["parameters"]["MaterialId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Material publicado y autorizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Material"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
        };
    };
    createViewerSession: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID único por intención; se conserva al reintentar la misma operación. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                materialId: components["parameters"]["MaterialId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    preferred_variant?: components["schemas"]["PageVariant"];
                };
            };
        };
        responses: {
            /** @description Sesión ligada a cuenta, sesión web, dispositivo y material. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ViewerSession"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyConflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    closeViewerSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                viewerSessionId: components["parameters"]["ViewerSessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión de lectura cerrada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    getViewerManifest: {
        parameters: {
            query?: {
                around_page?: number;
            };
            header?: never;
            path: {
                viewerSessionId: components["parameters"]["ViewerSessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadatos de lectura; nunca contiene una URL del PDF original. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ViewerManifest"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["ViewerUnavailable"];
        };
    };
    getViewerPage: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path: {
                viewerSessionId: components["parameters"]["ViewerSessionId"];
                pageNumber: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Imagen protegida; nunca es una variante limpia. */
            200: {
                headers: {
                    "Cache-Control"?: "private, no-store";
                    "Cross-Origin-Resource-Policy"?: "same-origin";
                    [name: string]: unknown;
                };
                content: {
                    "image/webp": string;
                    "image/avif": string;
                    "image/jpeg": string;
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["ViewerUnavailable"];
            429: components["responses"]["RateLimited"];
        };
    };
    adminListUsers: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                page_size?: components["parameters"]["PageSize"];
                query?: string;
                status?: components["schemas"]["UserStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de usuarios. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AdminRequired"];
        };
    };
    adminCreateUser: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID único por intención; se conserva al reintentar la misma operación. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Lucía Fernández",
                 *       "email": "lucia.f@email.com",
                 *       "access_until": "2026-08-25T23:59:59Z"
                 *     }
                 */
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Usuario creado. La contraseña inicial se muestra una sola vez. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CreatedUser"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AdminRequired"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    adminGetUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuario encontrado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminUser"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AdminRequired"];
            404: components["responses"]["NotFound"];
        };
    };
    adminUpdateUser: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID único por intención; se conserva al reintentar la misma operación. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Usuario actualizado y cambio auditado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminUser"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AdminRequired"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    adminExtendUserAccess: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID único por intención; se conserva al reintentar la misma operación. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "access_until": "2026-09-25T23:59:59Z",
                 *       "reason": "Renovación manual confirmada"
                 *     }
                 */
                "application/json": {
                    /** Format: date-time */
                    access_until: string;
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Extensión transaccional con before/after auditado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AccessExtension"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AdminRequired"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    adminListDocuments: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                page_size?: components["parameters"]["PageSize"];
                status?: components["schemas"]["DocumentStatus"];
                subject_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de documentos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDocumentPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AdminRequired"];
        };
    };
    adminUploadDocument: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID único por intención; se conserva al reintentar la misma operación. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    title: string;
                    subject_id: string;
                    type: components["schemas"]["MaterialType"];
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Archivo aceptado en cuarentena; todavía no está publicado. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminDocument"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AdminRequired"];
            409: components["responses"]["IdempotencyConflict"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMedia"];
            422: components["responses"]["ValidationError"];
        };
    };
    adminGetDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado actual del documento. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminDocument"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AdminRequired"];
            404: components["responses"]["NotFound"];
        };
    };
    adminUpdateDocument: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID único por intención; se conserva al reintentar la misma operación. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                    type?: components["schemas"]["MaterialType"];
                    archived?: boolean;
                };
            };
        };
        responses: {
            /** @description Documento actualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminDocument"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AdminRequired"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationError"];
        };
    };
}
